# Generated by Django 3.1.4 on 2020-12-28 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201228_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
    ]
