# Generated by Django 3.1.4 on 2020-12-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201228_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='article',
            name='first_paragraph',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='second_paragraph',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='third_paragraph',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
