# Generated by Django 3.1.4 on 2020-12-28 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20201228_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='first_paragraph',
            new_name='main_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='second_paragraph',
            new_name='second_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='third_paragraph',
            new_name='third_content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
